# Generated by Django 5.0.3 on 2024-06-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('order', models.CharField(max_length=200)),
                ('pickup_location', models.CharField(max_length=200)),
                ('delivery_location', models.IntegerField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=250)),
                ('item_description', models.CharField(max_length=200)),
            ],
        ),
    ]
