# Generated by Django 5.0.3 on 2024-06-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='delivery_location',
            field=models.CharField(max_length=200),
        ),
    ]
