# Generated by Django 5.0.3 on 2024-06-16 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_delivery_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='delivery_location',
            new_name='location',
        ),
    ]
