# Generated by Django 5.0.3 on 2024-06-16 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_delivery_location_user_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='delivery_location',
        ),
    ]
