# Generated by Django 5.0.3 on 2024-06-17 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_oder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oder',
            new_name='Order',
        ),
    ]
