# Generated by Django 5.0.3 on 2024-06-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_delivery_location_order_pickup_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='pic',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
