# Generated by Django 5.0.3 on 2024-07-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_user_username_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_completed',
        ),
    ]
