# Generated by Django 5.0.3 on 2024-07-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_order_item_description_alter_order_pickup_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='pic',
            field=models.ImageField(upload_to='rider_pics/'),
        ),
    ]
