# Generated by Django 5.0.3 on 2024-07-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_riderprofile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_location',
            field=models.TextField(default=''),
        ),
    ]
