# Generated by Django 5.0.7 on 2024-08-05 15:44

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receivers_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='order',
            name='senders_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
