# Generated by Django 5.0.7 on 2024-08-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_order_receivers_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receivers_phone_number',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='order',
            name='senders_phone_number',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
