# Generated by Django 5.1 on 2024-08-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_order_receivers_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('descripton1', models.TextField()),
                ('price', models.IntegerField()),
                ('descripton2', models.TextField()),
            ],
        ),
    ]
